# Generated by Django 3.0.3 on 2022-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('line_manager_emp_id', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_function', models.CharField(max_length=50)),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_region', models.CharField(max_length=50)),
                ('emp_post', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_status', models.BooleanField(default=False)),
                ('emp_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
