# Generated by Django 3.0.3 on 2022-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTCLEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verf_id', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('lmEmpId', models.CharField(max_length=50)),
                ('EmpId', models.CharField(max_length=50)),
                ('Functions', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
