# Generated by Django 4.0.6 on 2022-08-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220727_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PTCLEmployee',
        ),
    ]
